name: backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  mid_auth:
    path: /Users/osaxma/Projects/mid/components/mid_auth

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
