name: mid

packages:
  - packages/**

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  version: dart run scripts/generate_version.dart

  analyze:
    exec: dart analyze .

  format:
    exec: dart format -l 120 lib
