name: "mid_monorepo"
publish_to: none

executables:
  mid: mid_dev

environment:
  sdk: '>=2.17.6 <3.0.0'


dev_dependencies:
  mid:
    path: ./packages/mid/
  path: ^1.7.0
  yaml: ^3.1.0
  test: ^1.16.0

