name: mid_common
description: A common package used throughout mid project that contains constants and functions among other utilities
version: 0.0.2
homepage: https://www.github.com/osaxma/mid


environment:
  sdk: '>=2.17.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
