name: mid_server
description: a package for supporting servers that's built using mid
version: 0.0.1
homepage: https://github.com/osaxma/mid/

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  
dependencies: {mid: ^0.0.1, shelf: ^1.3.2, shelf_router: ^1.1.3, shelf_web_socket: ^1.0.2, web_socket_channel: ^2.2.0}


dependency_overrides:
  mid:
    path: ../mid