name: mid_protocol
description: A protocol for supporting the communication between mid servers and clients.
version: 0.0.2+3
homepage: https://www.github.com/osaxma/mid

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
