name: mid
description: a tool for building an end-to-end typesafe APIs in pure dart 
version: 0.1.0+2
homepage: https://www.github.com/osaxma/mid

executables:
  mid:

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  analyzer: ^4.3.1
  args: ^2.3.1
  built_collection: ^5.1.1
  cli_util: ^0.3.5
  code_builder: ^4.2.0
  dart3x: ^0.0.1+1
  dart_style: ^2.2.3
  meta: ^1.8.0
  mid_common: ^0.0.2
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.16.0
