name: mid
description: an API generation tool
version: 0.0.1
homepage: https://www.github.com/osaxma/mid

executable:
  mid:

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  analyzer: ^4.3.1
  args: ^2.3.1
  cli_util: ^0.3.5
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
