import 'dart:io';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

Future<void> main() async {
  final midProjectPath = p.join(Directory.current.path, 'packages', 'mid');

  final outputPath = p.join(midProjectPath, 'lib', 'version.dart');

  // ignore: avoid_print
  print('Updating version file @ $outputPath');
  final midPubspecPath = p.join(midProjectPath, 'pubspec.yaml');

  final pubspecContent = File(midPubspecPath).readAsStringSync();
  final yamlMap = loadYaml(pubspecContent) as YamlMap;

  final currentVersion = yamlMap['version'] as String;

  final fileContents = "// This file is generated by `scripts/updage_version.dart`. Do not edit manually.\n"
      "String midVersion = '$currentVersion';\n";

  await File(outputPath).writeAsString(fileContents);
  // ignore: avoid_print
  print('Updated version to $currentVersion in generated file $outputPath');
}
