name: mid_client
description: a package for supporting clients that are built using the mid package
version: 0.1.0+2
homepage: https://github.com/osaxma/mid/

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.5
  meta: ^1.8.0
  mid_common: ^0.0.2
  mid_protocol: ^0.1.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
