name: mid_auth
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  asn1lib: ^1.1.0
  collection: ^1.16.0
  corsac_jwt: ^1.0.0-nullsafety.1
  dbcrypt: ^2.0.0
  meta: ^1.8.0
  mid: ^0.0.1
  path: ^1.8.2
  sqlite3: ^1.7.2
  x509: ^0.2.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependency_overrides:
  mid:
    path: ../../packages/mid